modLoader="javafml"
loaderVersion="[43,)"
license="All Rights Reserved"

[[mods]]
modId="cosmostatic"
version="1.0.0"
displayName="Cosmostatic"
credits="Powered by MCreator"
displayURL="https://mcreator.net"
authors="SaNDRO"

[[dependencies.cosmostatic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




